config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :users, only: [:index, :update, :show]
  get 'avatar', to: "users#avatar"

  resources :products do
    resources :pictures, only: [:new]
    member do
      post 'like'
      post 'look'
      patch 'add'
      patch 'down'
    end
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end
  resources :pictures, only: [:show, :create, :destroy]

  resources :catalogs do
    member do
      get 'subcatalogs'
    end
  end

  resources :carts

  resources :line_items, only: [:create, :destroy]

  resources :orders do
    member do
      post :recieve, to: "orders#recieve"
      post :paytype, to: "orders#paytype"
      get :process, to: "orders#process_order"
    end
  end

  resources :recievers

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, Catalog
      can :manage, Cart, :user_id => user.id
      can :manage, LineItem, :cart_id => user.cart.id
      can [:create, :read, :update, :process_order, :recieve, :paytype], Order, :user_id => user.id
      can :manage, Picture, :user_id => user.id
      can [:show, :like, :look, :search], Product
      can :manage, Reciever, :user_id => user.id

    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :lineItems, dependent: :destroy
end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  validates :name, presence: true

  has_many :subcatalogs, class_name: Catalog, foreign_key: "parent_id" 
  belongs_to :parent, class_name: Catalog
  has_many :products

  def self.get(cata)
    result ||= []

    if cata.is_parent?
      Catalog.where(parent_id: cata.id).each do |c|
        self.get(c)
      end
    else
      result << cata
    end

  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  validates :count, presence: true

  belongs_to :cart
  belongs_to :product
end

app/models/look.rb
class Look < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderItems, dependent: :destroy
  belongs_to :reciever
  belongs_to :user

  STATE = %w(生成订单 填写收货人 待付款 待发货 已发货 确认收货 完成)

  def state_name
    STATE[self.state]
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :pic, styles: { small: "200x200#", medium: "500x500#", big: "800x800>" }, default_url: "/images/:style/missing.jpg"
  validates_attachment_content_type :pic, content_type: /\Aimage\/.*\Z/

  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :description, :price, :unit, :amount, presence: true
  validates :name, length: {maximum: 50}
  validates :unit, length: {maximum: 3}
  validates :price, :amount, numericality: true

  has_many :pictures, dependent: :destroy
  belongs_to :catalog
  has_many :likes, dependent: :destroy
  has_many :looks, dependent: :destroy

  default_scope {where(state: 2).order("created_at desc")}

  # accepts_nested_attributes_for :pictures

  STATE = %w(无图片 就绪 已上架 已下架)

  def state_name
    unless state.nil?
      STATE[state]
    else
      '无效'
    end
  end
end

app/models/reciever.rb
class Reciever < ActiveRecord::Base
  validates :name, :address, :telephone, presence: true
  has_many :orders, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: { message: "请填写名称" }
  validates :username, uniqueness: { message: "名称已经存在" }
  validates :username, length: { in: 2..10, message: "名称字数不能超过2~10个" }
  validates :agreement, acceptance: { message: "请在'我已阅读并同意用户注册协议'前打勾" }

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_one :cart, dependent: :destroy
  has_one :reciever, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :likes, dependent: :destroy



  alias_method :cart_base, :cart

  def cart
    self.cart_base || create_cart
  end

  # 管理员
  ADMINS = %w(admin@guoshu.com ynzkai@gmail.com)

  def admin?
    ADMINS.include?(self.email) ? true : false
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
  def catalog_links(c)

    if c.parent
      p = Catalog.find c.parent
      catalog_links(p) + ' / ' + link_to(c.name, catalog_path(c.id))
    else
      link_to '首页', root_url
    end
  end

  def get_catalogs
    catalogs = {}
    parent_catalogs = Catalog.where(parent_id: Catalog.find_by(name: '分类').id)
    parent_catalogs.each do |c|
      cs = Catalog.where parent_id: c.id
      catalogs[c] = cs.to_a
    end
    return catalogs
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/helpers/recievers_helper.rb
module RecieversHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guoshu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/toolbar' %>

<%= render 'shared/sidebar' %>

<%= yield %>

<%= render 'shared/foot' %>

</body>
</html>

app/views/shared/_foot.html.erb
<div class="container-fluid foot">
  <div class="container">
    <div class="row links">
      <div class="col-md-3 col-sm-6">
        <h4>友情链接</h4>
        <ul>
          <li>友情链接</li>
          <li>友情链接</li>
          <li>友情链接</li>
        </ul>
      </div>

      <div class="col-md-3 col-sm-6">
        <h4>合作伙伴</h4>
        <ul>
          <li>合作伙伴</li>
          <li>合作伙伴</li>
          <li>合作伙伴</li>
        </ul>
      </div>

      <div class="col-md-3 col-sm-6">
        <h4>关于我们</h4>
        <ul>
          <li>关于我们</li>
          <li>联系方式</li>
          <li>帮助中心</li>
        </ul>
      </div>

      <div class="col-md-3 col-sm-6">
	    <div>[此处二维码]</div>
	    <div>QQ: 916282079</div>
      </div>
    </div>

	<div class="row copyright">
	  <p>Copyright © 2015-2015 文山果蔬网(http://www.wsguoshu.com) 版权所有 All Rights Reserved.</p>
	</div>
  </div>
</div>

app/views/shared/_head.html.erb
  <div class="row head-bar">
	<div class="col-md-2 logo">
	  [the logo placeholder]
	</div>

	<div class="col-md-4 slogen">
	  果蔬生鲜,文山人的网上菜市!
	</div>

	<div class="col-md-4 search">

		<%= search_form_for @q, url: search_products_path, html: {method: :post, class: "navbar-form navbar-left"} do |f| %>
		<%= f.search_field :name_or_description_cont %>
		<%= f.submit "搜索" %>
	  <% end %>
	</div>
	<div class="col-md-2 info">
		<p>微信</p>
		<p>QQ</p>
		<p>电话</p>
	</div>
  </div>

  <%= render "shared/navstrip" %>

app/views/shared/_navstrip.html.erb
  <div class="row">
	<div class="col-md-12 nav-strip">
	  <ul>
		<li><%= link_to "分类", catalogs_path %></li>
		<li data-no-turbolink><%= link_to "首页", root_path %></li>
	    <li><a href="#">组合区</a></li>
	    <li><a href="#">推荐区</a></li>
	    <li><a href="#">畅销区</a></li>
	    <li><a href="#">折扣区</a></li>
	    <li><a href="#">营养搭配</a></li>
	    <li><a href="#">食谱精选</a></li>
	  </ul>
	</div>
  </div>

app/views/shared/_sidebar.html.erb
<div class="sidebar-wrapper">
  <div class="sidebar">
	<% if user_signed_in? %>
	  <%= link_to cart_path(current_user.cart) do %>
        <div id="cart" class="cart">
          <span class="glyphicon glyphicon-shopping-cart"></span>
	      <div class="point <%= current_user.cart.lineItems.count > 0 ? 'show' : 'hidden' %>"></div>
        </div>
	  <% end %>
	<% end %>
  
    <div id="go-top" class="top">
      <span class="glyphicon glyphicon-menu-up"></span>
    </div>
	<div data-no-turbolink>
	</div>
  </div>
  
  <div id="cart-line-items">
  </div>
</div>

app/views/shared/_toolbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1" data-no-turbolink>
      <ul class="nav navbar-nav">
		<li data-no-turbolink><%= link_to "文山果蔬网用心为您服务!", root_path, class: "navbar-brand" %></li>
        <li><a href="#">关于我们</a></li>
      </ul>
	  <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
		<% if current_user.admin? %>
		  <li><%= link_to '产品列表', products_path %></li>
		  <li><%= link_to '增加产品', new_product_path %></li>
		<% end %>

        <li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
		    <li><%= link_to '我的主页', user_path(current_user) %></li>
		    <li><%= link_to '修改头像', avatar_path %></li>
		    <li><%= link_to '修改资料', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
		    <li><%= link_to '退出', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
	  <% else %>
        <ul class="nav navbar-nav pull-right">
		  <li><%= link_to '登录', new_user_session_path %></li>
		  <li><%= link_to '注册', new_user_registration_path %></li>
		</ul>
	  <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>