config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :users, only: [:index, :update, :show]
  get 'avatar', to: "users#avatar"

  resources :products do
    resources :pictures, only: [:new]
    member do
      post 'like'
      post 'look'
      patch 'add'
      patch 'down'
    end
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end
  resources :pictures, only: [:show, :create, :destroy]

  resources :catalogs do
    member do
      get 'subcatalogs'
    end
  end

  resources :carts

  resources :line_items, only: [:create, :destroy]

  resources :orders do
    member do
      post :recieve, to: "orders#recieve"
      post :paytype, to: "orders#paytype"
      get :process, to: "orders#process_order"
    end
  end

  resources :recievers

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderItems, dependent: :destroy
  belongs_to :reciever
  belongs_to :user

  STATE = %w(生成订单 填写收货人 待付款 待发货 已发货 确认收货 完成)

  def state_name
    STATE[self.state]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource :order

  # 0生成订单 1填写收货人 2待付款 3待发货 4已发货 5确认收货 完成
  def process_order
    @order = Order.find params[:id]
    case @order.state
    when 0
      render 'recieve'
    when 1
      render 'paytype'
    when 2
      pay
    when 3
      @order.update state: 4
      respond_to do |format|
        format.js { render :update_state }
      end
    when 4
      @order.update state: 5
      respond_to do |format|
        format.js { render :update_state }
      end
    when 5
      @order.update state: 6
      respond_to do |format|
        format.js { render :update_state }
      end
    else
      redirect_to :back
    end
  end

  def index
    @orders = current_user.orders
  end

  def show
  end

  def new
  end

  def edit
  end

  def paytype
    @order = Order.find params[:id]
    if @order.update pay_type: params[:order][:pay_type]
      if params[:order][:pay_type] == "0"
        @order.update state: 3
        # 货到付款
        render 'finish_order'
      else
        @order.update state: 2
        # 支付宝
      end
    end
  end

  def pay
  end

  def recieve
    @order = Order.find params[:id]
    if @order.reciever.update reciever_params
      @order.update state: 1
      render 'paytype'
    end
  end

  def create
    if current_user.cart.lineItems.count <= 0
      render 'carts/show'
      return
    end

    if current_user.reciever.nil?
      @reciever = Reciever.new user_id: current_user.id
      @reciever.save(validate: false)
    else
      @reciever = current_user.reciever
    end

    names = current_user.cart.lineItems.inject('') {|s, e| s+e.product.name+';'}
    total = current_user.cart.lineItems.inject(0) { |sum, e| sum + e.count * e.product.price }
    @order = current_user.orders.create title: names, total: total, reciever_id: @reciever.id
    current_user.cart.lineItems.each do |item|
      @order.orderItems.create product_id: item.product_id, count: item.count
    end
    current_user.cart.lineItems.delete_all
    render 'recieve'
  end

  def destroy
  end

  def update
  end

  protected

    def reciever_params
      params.require(:reciever).permit(:name, :address, :telephone)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order.html.erb
<tr>
  <td><%= order.id %></td>
  <td class="order-title"><%= order.title %></td>
  <td><%= order.total %></td>
  <td id="order<%= order.id %>"><%= order.state_name %></td>
  <td><%= order.created_at %></td>

  <td>
  <% if current_user.admin? %>
	<% if [3,5].include?(order.state) %>
	  <%= link_to '处理', process_order_path(order.id), remote: true, data: {confirm: '确定提交订单到下一环节？'} %>
	<% end %>
  <% else %>
	<% if order.state == 4 %>
	  <%= link_to '处理', process_order_path(order.id), remote: true, data: {confirm: '确定提交订单到下一环节？'} %>
    <% end %>
	<% unless [3,4,5,6].include? order.state %>
      <%= link_to '处理', process_order_path(order.id) %>
    <% end %>
  <% end %>
  </td>
</tr>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/finish_order.html.erb
<div class="container">
  <div class="row">
	<div class="col-md-12">
	  <%= render "shared/navstrip" %>

	  <h3 class="text-warning text-center">感谢您的光顾,我们很快会为您送货上门.</h3>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
	<div class="col-md-12">
	  <table class="orders table table-bordered table-hover">
		<thead>
		  <th>ID</th>
		  <th>名称</th>
		  <th>金额(元)</th>
		  <th>状态</th>
		  <th>时间</th>
		  <th>操作</th>
		</thead>
		<tbody>
		  <%= render @orders %>
		</tbody>
	  </table>
	</div>
  </div>
</div>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/pay.html.erb
<div class="container">
  <div class="row order">
    <%= render "shared/navstrip" %>

	<div class="pay col-md-4 col-md-offset-4 col-sm-12">
	  <h4 class="text-warning">请选择付款方式:</h4><br/>
	  <%= form_for :order, url: pay_order_path(@order) do |f| %>
		<div class="form-group">
		  <%= f.label :pay_type do %>
		    <%= f.radio_button :pay_type, 0 %> <span>货到付款</span>
		  <% end %>
		</div>

	    <h5 class="text-danger">暂不支持支付宝付款</h5>

	    <div class="form-group">
		  <%= f.label :pay_type do %>
		    <%= f.radio_button :pay_type, 1, disabled: true %> <span>支付宝付款</span>
		  <% end %>
		</div>

	    <%= f.submit '提交订单', class: "btn btn-danger" %>
	  <% end %>
	</div>
  </div>
</div>

app/views/orders/paytype.html.erb
<div class="container">
  <div class="row order">
    <%= render "shared/navstrip" %>

	<div class="pay col-md-4 col-md-offset-4 col-sm-12">
	  <h4 class="text-warning">请选择付款方式:</h4><br/>
	  <%= form_for :order, url: paytype_order_path(@order) do |f| %>
		<div class="form-group">
		  <%= f.label :pay_type do %>
		    <%= f.radio_button :pay_type, 0 %> <span>货到付款</span>
		  <% end %>
		</div>

	    <h5 class="text-danger">暂不支持支付宝付款</h5>

	    <div class="form-group">
		  <%= f.label :pay_type do %>
		    <%= f.radio_button :pay_type, 1, disabled: true %> <span>支付宝付款</span>
		  <% end %>
		</div>

	    <%= f.submit '提交订单', class: "btn btn-danger" %>
	  <% end %>
	</div>
  </div>
</div>

app/views/orders/recieve.html.erb
<div class="container">
  <div class="row order">
    <%= render "shared/navstrip" %>

	<div class="reciever col-md-4 col-md-offset-4 col-sm-12">
	
	  <h4 class="text-warning">请填写收货人信息</h4><br/>

      <%= form_for :reciever, url: recieve_order_path(@order), method: :post do |f| %>

        <% if @order.reciever.errors.any? %>
          <div id="error_explanation">
            <ul>
            <% @order.reciever.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name, '收货人姓名' %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :address, '地址' %>
          <%= f.text_field :address, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :telephone, '联系电话' %>
          <%= f.text_field :telephone, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= submit_tag '确定->去付款', class: "btn btn-danger pull-right" %>
        </div>
      <% end %>

	</div>
  </div>
</div>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/orders/update_state.js.erb
$("#order<%= @order.id %>").html("<%= @order.state_name %>");