config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :users, only: [:index, :update, :show]
  get 'avatar', to: "users#avatar"

  resources :products do
    resources :pictures, only: [:new]
    member do
      post 'like'
      post 'look'
      patch 'add'
      patch 'down'
    end
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end
  resources :pictures, only: [:show, :create, :destroy]

  resources :catalogs do
    member do
      get 'subcatalogs'
    end
  end

  resources :carts

  resources :line_items, only: [:create, :destroy]

  resources :orders do
    member do
      post :recieve, to: "orders#recieve"
      post :paytype, to: "orders#paytype"
      get :process, to: "orders#process_order"
    end
  end

  resources :recievers

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :description, :price, :unit, :amount, presence: true
  validates :name, length: {maximum: 50}
  validates :unit, length: {maximum: 3}
  validates :price, :amount, numericality: true

  has_many :pictures, dependent: :destroy
  belongs_to :catalog
  has_many :likes, dependent: :destroy
  has_many :looks, dependent: :destroy

  default_scope {where(state: 2).order("created_at desc")}

  # accepts_nested_attributes_for :pictures

  STATE = %w(无图片 就绪 已上架 已下架)

  def state_name
    unless state.nil?
      STATE[state]
    else
      '无效'
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :search]
  before_action :set_product, only: [:show, :edit, :update, :destroy, :like, :look, :add, :down]
  load_and_authorize_resource :product

  # GET /products
  # GET /products.json
  def index
    @products = Product.unscoped.all.reverse
  end

  # GET /products/1
  # GET /products/1.json
  def show
    if user_signed_in?
      @product.looks.create(user_id: current_user.id)
    else
      @product.looks.create
    end
  end

  # GET /products/new
  def new
    @product = Product.new
    @parent_catalogs = Catalog.where parent: Catalog.find_by(name: '分类').id
    @catalogs = Catalog.where parent: @parent_catalogs.first.id
  end

  # GET /products/1/edit
  def edit
    @parent_catalogs = Catalog.where parent: Catalog.find_by(name: '分类').id
    @catalogs = Catalog.where parent: @parent_catalogs.first.id
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to new_product_picture_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    like_item = @product.likes.find_by(user_id: current_user.id)
    if like_item
      @product.likes.destroy like_item
    else
      @product.likes.create(user_id: current_user.id)
    end

    @likes = @product.likes.count
    respond_to do |format|
      format.js
    end
  end

  def add
    @product.update state: 2
    respond_to do |format|
      format.js
    end
  end

  def down
    @product.update state: 3
    respond_to do |format|
      format.js
    end
  end

  def search
    @q = Product.ransack(params[:q])
    @products = @q.result.includes(:catalog)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.unscoped.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :unit, :amount, :pic, :catalog_id, :state)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @product do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
    
          <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <%= f.hidden_field :state %>
    
      <div class="form-group">
        <%= f.label :catalog %><br>
    	<%= select_tag :parent_catalog, options_from_collection_for_select(@parent_catalogs, "id", "name"), class: "form-control" %>
	  </div>
      <div class="form-group">
		<%= f.select :catalog_id, options_from_collection_for_select(@catalogs, "id", "name"), {include_blank: false}, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :price %><br>
        <%= f.text_field :price, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :unit %><br>
        <%= f.text_field :unit, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :amount %><br>
        <%= f.number_field :amount, class: "form-control" %>
      </div>
      <div class="actions">
        <%= f.submit '提交', class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_icons.html.erb
<div class="icons">
  <span class="look glyphicon glyphicon-eye-open"></span>
  <span id="looks<%= product.id %>"><%= product.looks.count %></span>

  <% if user_signed_in? %>
    <%= link_to like_product_url(product), remote: true, method: :post do %>
      <span class="glyphicon glyphicon-heart"></span>
    <% end %>
  <% else %>
    <span class="like glyphicon glyphicon-heart"></span> 
  <% end %>
  <span id="likes<%= product.id %>"><%= product.likes.count %></span>

</div>

app/views/products/_product.html.erb
<div class="col-sm-6 col-md-3">
  <div class="thumbnail product-box" data-no-turbolink>
	<%= link_to product_path(product) do %>
	  <%= image_tag product.pictures.first.pic.url(:medium) %>
	<% end %>

	<div class="caption">
	  <div class="row product-name">
	    <div class="col-xs-4">名称:</div>
		<div class="col-xs-8"><%= truncate product.name, length: 13 %></div>
	  </div>

	  <div class="row product-price">
		<div class="col-xs-4">价格:</div>
		<div class="col-xs-8">¥ <%= product.price %> 元/<%= product.unit %></div>
	  </div>

	  <div class="row product-amount">
		<div class="col-xs-4">数量:</div>
		<div class="col-xs-8"><%= product.amount %></div>
	  </div>

	  <div class="row buttons">
	    <div class="col-xs-7">
		  <%= render 'products/icons', product: product %>
	    </div>

	    <div class="col-xs-5 buy">
	      <%= hidden_field_tag :product_id, product.id %>

	      <% if user_signed_in? %>
	        <%= link_to "#", class: "addtocart-button-sm" do %>
			  <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
			  <span>加入购物车</span>
			<% end %>
	      <% else %>
	        <%= link_to new_user_session_path do %>
			  <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
			  <span>加入购物车</span>
		    <% end %>
	      <% end %>
	    </div>
	  </div>

	</div>
  </div>
</div>

app/views/products/_product_item.html.erb
<tr id="product<%= product.id %>" class="product">
  <td><%= image_tag product.pictures.first.pic.url(:small), class: "picture" %></td>
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td><%= product.price %></td>
  <td><%= product.unit %></td>
  <td><%= product.amount %></td>
  <td><%= product.state_name %></td>

  <% if ['就绪', '已下架'].include? product.state_name %>
    <td><%= link_to '上架', add_product_path(product), method: :patch, remote: true %></td>
  <% end %>
  <% if '已上架' == product.state_name %>
    <td><%= link_to '下架', down_product_path(product), method: :patch, remote: true %></td>
  <% end %>

  <td><%= link_to 'Show', product %></td>
  <td><%= link_to 'Edit', edit_product_path(product) %></td>
  <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/products/add.js.erb
$("#product<%= @product.id %>").replaceWith("<%= j render 'product_item', product: @product %>")

app/views/products/down.js.erb
$("#product<%= @product.id %>").replaceWith("<%= j render 'product_item', product: @product %>")

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>商品清单</h1>

<table class="table table-striped products-list">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Unit</th>
      <th>Amount</th>
      <th>State</th>
      <th colspan="4">Action</th>
    </tr>
  </thead>

  <tbody>
	<% @products.each do |product| %>
	  <%= render 'product_item', product: product %>
	<% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>
</div>

app/views/products/like.js.erb
$("#likes<%= @product.id %>").html('<%= @likes %>');

app/views/products/new.html.erb
<div class="container">
  <h1>New Product</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Back', products_path %>
</div>

app/views/products/search.html.erb
<div class="container">
  <%= render "shared/head" %>

  <div class="row">
	<div class="col-md-12 wrapper search-result">
	  <% unless @products.count == 0 %>
		<div class="sort-strip">
		  <span>为您找到 <%= @products.count %> 种商品。</span>
		  <div class="links">
		    <%= sort_link(@q, :name, '名称') %>
		    <%= sort_link(@q, :price, '价格') %>
		    <%= sort_link(@q, :catalog_id, '类型') %>
		    <%= sort_link(@q, :created_at, '日期', default_order: :desc) %>
		  </div>
		</div>
	    <%= render @products %>
	  <% else %>
		<h4 class="text-warning text-center"> 暂没找到您要的商品，请稍后再来看看。</h4>
	  <% end %>
	</div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <%= render "shared/navstrip" %>
  
  <div class="row">
	<div class="col-md-12 catalog-level" data-no-turbolink>
	  <%= catalog_links(@product.catalog) %>
	</div>
  </div>

  <div class="row product-detail">
	<div class="col-md-8">

      <div class="thumbnail">
        <% @product.pictures.each do |p| %>
      	<%= image_tag p.pic.url(:big) %>
        <% end %>
      </div>

      <div class="description">
        <%= @product.description %>
      </div>
	</div>

	<div class="col-md-4">
	  <div class="product-info">
	    <div class="row product-name">
	      <div class="col-xs-3">名称:</div>
	      <div class="col-xs-9"><%= @product.name %></div>
	    </div>

	    <div class="row product-price">
	      <div class="col-xs-3">价格:</div>
	      <div class="col-xs-9">¥ <%= @product.price %> 元/<%= @product.unit %></div>
	    </div>

	    <div class="row product-amount">
	      <div class="col-xs-3">数量:</div>
	      <div class="col-xs-9"><%= @product.amount %></div>
	    </div>

	    <%= render 'icons', product: @product %>
	  </div>

	  <div class="buy">
		<%= form_for :item, url: line_items_path do |f| %>
		  <%= hidden_field_tag :product_id, @product.id %>
		  <%= label_tag "购买数量" %>
	      <%= number_field_tag :buycount, 1, min: 1, max: @product.amount %>

	      <div class="buy-buttons">
		    <%= f.submit '立即购买',  class: "btn btn-danger btn-lg buy-button" %>
		    <% if user_signed_in? %>
	          <%= link_to '加入购物车', "#", class: "btn btn-default btn-lg addtocart-button" %>
		    <% else %>
	          <%= link_to '加入购物车', new_user_session_path, class: "btn btn-default btn-lg" %>
		    <% end %>
	      </div>
		<% end %>
	  </div>
	</div>

  </div>
</div>